version: "3.9"

services:
  app:
    build: .
    container_name: project2_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:7
    container_name: project2_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
