<<<<<<< Updated upstream
services:
  api:
    image: daun104/project2-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
=======

services:
  app:
    build: .
    container_name: project2_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:7
    container_name: project2_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
>>>>>>> Stashed changes
