version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project2_app
    ports:
      - "3000:3000"   # host:container
    env_file:
      - .env.prod     # Load secrets at runtime
    depends_on:
      - mongo
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: project2_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
